import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QFileDialog, QMessageBox    #新增
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ShouJuan(QMainWindow):
    def __init__(self):  # 新增
        super(Ui_ShouJuan, self).__init__()  # 新增
        self.setupUi(self)  # 新增

    def setupUi(self, ShouJuan):
        ShouJuan.setObjectName("ShouJuan")
        ShouJuan.resize(542, 612)
        ShouJuan.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(ShouJuan)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(60, 10, 431, 41))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 429, 39))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.radioButton_2.setGeometry(QtCore.QRect(320, 10, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.radioButton.setGeometry(QtCore.QRect(230, 10, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setGeometry(QtCore.QRect(60, 10, 141, 21))
        self.label.setObjectName("label")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(160, 60, 61, 21))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(380, 60, 61, 21))
        self.label_35.setObjectName("label_35")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 80, 471, 451))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 2, 0)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_17 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_17.setObjectName("doubleSpinBox_17")
        self.gridLayout.addWidget(self.doubleSpinBox_17, 12, 4, 1, 2)
        self.doubleSpinBox_16 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_16.setObjectName("doubleSpinBox_16")
        self.gridLayout.addWidget(self.doubleSpinBox_16, 0, 1, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setIndent(30)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 7, 0, 1, 1)
        self.doubleSpinBox_26 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_26.setObjectName("doubleSpinBox_26")
        self.gridLayout.addWidget(self.doubleSpinBox_26, 5, 4, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setIndent(30)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 3, 1, 1)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout.addWidget(self.doubleSpinBox_5, 5, 1, 1, 2)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        self.label_26.setIndent(30)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 10, 3, 1, 1)
        self.doubleSpinBox_21 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_21.setObjectName("doubleSpinBox_21")
        self.gridLayout.addWidget(self.doubleSpinBox_21, 4, 4, 1, 2)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        self.label_23.setIndent(30)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 11, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setIndent(30)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setIndent(30)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 8, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        self.label_30.setIndent(30)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 5, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setIndent(30)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 6, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget)
        self.label_33.setIndent(30)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 13, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setIndent(30)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setIndent(30)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 0, 1, 1)
        self.doubleSpinBox_18 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_18.setObjectName("doubleSpinBox_18")
        self.gridLayout.addWidget(self.doubleSpinBox_18, 11, 4, 1, 2)
        self.doubleSpinBox_24 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_24.setObjectName("doubleSpinBox_24")
        self.gridLayout.addWidget(self.doubleSpinBox_24, 6, 4, 1, 2)
        self.doubleSpinBox_31 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_31.setObjectName("doubleSpinBox_31")
        self.gridLayout.addWidget(self.doubleSpinBox_31, 15, 4, 1, 2)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        self.label_25.setIndent(30)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 12, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setIndent(30)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 3, 1, 1)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout.addWidget(self.doubleSpinBox_8, 8, 1, 1, 2)
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.gridLayout.addWidget(self.doubleSpinBox_10, 10, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setIndent(30)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget)
        self.label_28.setIndent(30)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 14, 0, 1, 1)
        self.doubleSpinBox_20 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_20.setObjectName("doubleSpinBox_20")
        self.gridLayout.addWidget(self.doubleSpinBox_20, 2, 4, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setIndent(30)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 13, 0, 1, 1)
        self.doubleSpinBox_28 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_28.setObjectName("doubleSpinBox_28")
        self.gridLayout.addWidget(self.doubleSpinBox_28, 13, 4, 1, 2)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget)
        self.label_29.setIndent(30)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 14, 3, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 1, 1, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setIndent(30)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 8, 0, 1, 1)
        self.doubleSpinBox_30 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_30.setObjectName("doubleSpinBox_30")
        self.gridLayout.addWidget(self.doubleSpinBox_30, 0, 4, 1, 2)
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.gridLayout.addWidget(self.doubleSpinBox_12, 12, 1, 1, 2)
        self.doubleSpinBox_29 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_29.setObjectName("doubleSpinBox_29")
        self.gridLayout.addWidget(self.doubleSpinBox_29, 9, 4, 1, 2)
        self.doubleSpinBox_32 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_32.setObjectName("doubleSpinBox_32")
        self.gridLayout.addWidget(self.doubleSpinBox_32, 7, 4, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setIndent(30)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 9, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setIndent(30)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setIndent(30)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 9, 0, 1, 1)
        self.doubleSpinBox_14 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_14.setObjectName("doubleSpinBox_14")
        self.gridLayout.addWidget(self.doubleSpinBox_14, 14, 1, 1, 2)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget)
        self.label_31.setIndent(30)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 7, 3, 1, 1)
        self.doubleSpinBox_23 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_23.setObjectName("doubleSpinBox_23")
        self.gridLayout.addWidget(self.doubleSpinBox_23, 10, 4, 1, 2)
        self.doubleSpinBox_22 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_22.setObjectName("doubleSpinBox_22")
        self.gridLayout.addWidget(self.doubleSpinBox_22, 8, 4, 1, 2)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout.addWidget(self.doubleSpinBox_6, 6, 1, 1, 2)
        self.doubleSpinBox_27 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_27.setObjectName("doubleSpinBox_27")
        self.gridLayout.addWidget(self.doubleSpinBox_27, 3, 4, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setIndent(30)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget)
        self.label_27.setIndent(30)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 15, 0, 1, 1)
        self.doubleSpinBox_19 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_19.setObjectName("doubleSpinBox_19")
        self.gridLayout.addWidget(self.doubleSpinBox_19, 1, 4, 1, 2)
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.gridLayout.addWidget(self.doubleSpinBox_11, 11, 1, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setIndent(30)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 10, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setIndent(30)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 3, 1, 1)
        self.doubleSpinBox_15 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_15.setObjectName("doubleSpinBox_15")
        self.gridLayout.addWidget(self.doubleSpinBox_15, 15, 1, 1, 2)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout.addWidget(self.doubleSpinBox_7, 7, 1, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setIndent(30)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 11, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setIndent(30)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 3, 1, 1)
        self.doubleSpinBox_25 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_25.setObjectName("doubleSpinBox_25")
        self.gridLayout.addWidget(self.doubleSpinBox_25, 14, 4, 1, 2)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget)
        self.label_32.setIndent(30)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 15, 3, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 2, 1, 1, 2)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout.addWidget(self.doubleSpinBox_4, 4, 1, 1, 2)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.gridLayout.addWidget(self.doubleSpinBox_9, 9, 1, 1, 2)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setIndent(30)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 12, 0, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout.addWidget(self.doubleSpinBox_3, 3, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setIndent(30)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setIndent(30)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 3, 1, 1)
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.gridLayout.addWidget(self.doubleSpinBox_13, 13, 1, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(360, 540, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 540, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.layoutWidget.raise_()
        self.scrollArea_2.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        ShouJuan.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ShouJuan)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 542, 22))
        self.menubar.setObjectName("menubar")
        ShouJuan.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ShouJuan)
        self.statusbar.setObjectName("statusbar")
        ShouJuan.setStatusBar(self.statusbar)

        self.retranslateUi(ShouJuan)
        self.pushButton.clicked.connect(ShouJuan.close)
        self.pushButton_2.clicked.connect(ShouJuan.close)
        QtCore.QMetaObject.connectSlotsByName(ShouJuan)

    def retranslateUi(self, ShouJuan):
        _translate = QtCore.QCoreApplication.translate
        ShouJuan.setWindowTitle(_translate("ShouJuan", "刀具编辑"))
        self.radioButton_2.setText(_translate("ShouJuan", "下轴"))
        self.radioButton.setText(_translate("ShouJuan", "上轴"))
        self.label.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:14pt;\">1号卷位置</span></p></body></html>"))
        self.label_34.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:12pt;\">宽度/mm</span></p></body></html>"))
        self.label_35.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:12pt;\">宽度/mm</span></p></body></html>"))
        self.label_15.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">7号位</span></p></body></html>"))
        self.label_10.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">16号位</span></p></body></html>"))
        self.label_26.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">25号位</span></p></body></html>"))
        self.label_23.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">26号位</span></p></body></html>"))
        self.label_4.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">2号位</span></p></body></html>"))
        self.label_17.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">23号位</span></p></body></html>"))
        self.label_30.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">20号位</span></p></body></html>"))
        self.label_14.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">21号位</span></p></body></html>"))
        self.label_33.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">28号位</span></p></body></html>"))
        self.label_11.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">5号位</span></p></body></html>"))
        self.label_13.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">6号位</span></p></body></html>"))
        self.label_25.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">27号位</span></p></body></html>"))
        self.label_5.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">17号位</span></p></body></html>"))
        self.label_2.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">1号位</span></p></body></html>"))
        self.label_28.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">14号位</span></p></body></html>"))
        self.label_19.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">13号位</span></p></body></html>"))
        self.label_29.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">29号位</span></p></body></html>"))
        self.label_16.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">8号位</span></p></body></html>"))
        self.label_21.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">24号位</span></p></body></html>"))
        self.label_9.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">4号位</span></p></body></html>"))
        self.label_18.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">9号位</span></p></body></html>"))
        self.label_31.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">22号位</span></p></body></html>"))
        self.label_6.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">3号位</span></p></body></html>"))
        self.label_27.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">15号位</span></p></body></html>"))
        self.label_20.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">10号位</span></p></body></html>"))
        self.label_7.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">18号位</span></p></body></html>"))
        self.label_22.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">11号位</span></p></body></html>"))
        self.label_12.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">19号位</span></p></body></html>"))
        self.label_32.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">30号位</span></p></body></html>"))
        self.label_24.setText(_translate("ShouJuan", "<html><head/><body><p><span style=\" font-size:10pt;\">12号位</span></p></body></html>"))
        self.label_3.setText(_translate("ShouJuan", "<html><head/><body><p>左边料</p></body></html>"))
        self.label_8.setText(_translate("ShouJuan", "<html><head/><body><p>  右边料</p></body></html>"))
        self.pushButton.setText(_translate("ShouJuan", "保存"))
        self.pushButton_2.setText(_translate("ShouJuan", "取消"))

# if __name__ == "__main__":              #新增
#     app = QApplication(sys.argv)        #新增
#     form = Ui_ShouJuan()               #新增
#     form.show()                         #新增
#     sys.exit(app.exec_())               #新增